import type { CrudConfig } from './types';

const questionnaireTextFields: Array<{
  key: string;
  label: string;
  section: string;
  required?: boolean;
}> = [
  { key: 'name', label: 'Name', section: 'Basic', required: true },
  { key: 'introParagraph', label: 'Intro paragraph', section: 'Intro copy', required: true },
  { key: 'personalIntroParagraph', label: 'Personal intro', section: 'Intro copy' },
  { key: 'teamIntroParagraph', label: 'Team intro', section: 'Intro copy' },
  { key: 'leaderteamIntroParagraph', label: 'Leader team intro', section: 'Intro copy' },
  { key: 'companyIntroParagraph', label: 'Company intro', section: 'Intro copy', required: true },
  { key: 'companyEndParagraph', label: 'Company end', section: 'End copy', required: true },
  { key: 'personalEndParagraph', label: 'Personal end', section: 'End copy', required: true },
  { key: 'teamEndParagraph', label: 'Team end', section: 'End copy' },
  { key: 'personalReportHeading', label: 'Personal report heading', section: 'Report headings' },
  { key: 'personalGraphicHeading', label: 'Personal graphic heading', section: 'Report headings' },
  { key: 'teamReportHeading', label: 'Team report heading', section: 'Report headings' },
  { key: 'leaderteamReportHeading', label: 'Leader team report heading', section: 'Report headings' },
  { key: 'teamGraphicHeading', label: 'Team graphic heading', section: 'Report headings' },
  { key: 'leaderteamGraphicHeading', label: 'Leader team graphic heading', section: 'Report headings' },
  { key: 'companyReportHeading', label: 'Company report heading', section: 'Report headings' },
  { key: 'companyGraphicHeading', label: 'Company graphic heading', section: 'Report headings' },
  { key: 'personalReportDetailHeading', label: 'Personal detail heading', section: 'Detail headings' },
  { key: 'teamReportDetailHeading', label: 'Team detail heading', section: 'Detail headings' },
  { key: 'leaderteamReportDetailHeading', label: 'Leader team detail heading', section: 'Detail headings' },
  { key: 'companyReportDetailHeading', label: 'Company detail heading', section: 'Detail headings' },
  { key: 'reportHowToIndividual', label: 'How-to (individual)', section: 'Report guidance' },
  { key: 'reportHowToTeam', label: 'How-to (team)', section: 'Report guidance' },
  { key: 'reportHowToLeaderteam', label: 'How-to (leader team)', section: 'Report guidance' },
  { key: 'reportHowToCompany', label: 'How-to (company)', section: 'Report guidance' },
  { key: 'reportNextStepsIndividual', label: 'Next steps (individual)', section: 'Report guidance' },
  { key: 'reportNextStepsTeam', label: 'Next steps (team)', section: 'Report guidance' },
  { key: 'reportNextStepsLeaderteam', label: 'Next steps (leader team)', section: 'Report guidance' },
  { key: 'reportNextStepsCompany', label: 'Next steps (company)', section: 'Report guidance' },
];

export const CRUD_CONFIGS: Record<string, CrudConfig> = {
  questionnaires: {
    title: 'Questionnaires',
    description: 'Manage questionnaire copy, headings, and report templates.',
    listPath: '/admin/questionnaires',
    createPath: '/admin/questionnaires',
    updatePath: (id) => `/admin/questionnaires/${id}`,
    deletePath: (id) => `/admin/questionnaires/${id}`,
    getPath: (id) => `/admin/questionnaires/${id}`,
    fields: questionnaireTextFields.map((f) => ({
      key: f.key,
      label: f.label,
      type: f.key === 'name' ? ('text' as const) : ('textarea' as const),
      required: f.required,
      inTable: f.key === 'name',
      section: f.section,
      defaultValue: f.key === 'name' ? '' : '<p></p>',
    })),
  },
  elements: {
    title: 'Elements',
    description: 'Catalog elements grouped by questionnaire and part.',
    listPath: '/admin/elements',
    createPath: '/admin/elements',
    updatePath: (id) => `/admin/elements/${id}`,
    deletePath: (id) => `/admin/elements/${id}`,
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, inTable: true, section: 'Basic' },
      {
        key: 'questionnaireId',
        label: 'Questionnaire',
        type: 'select',
        required: true,
        inTable: true,
        optionsKey: 'questionnaires',
        section: 'Basic',
      },
      { key: 'group', label: 'Group (1–3)', type: 'number', required: true, inTable: true, section: 'Basic', defaultValue: 1 },
      { key: 'order', label: 'Order', type: 'number', required: true, inTable: true, section: 'Basic', defaultValue: 1 },
      { key: 'shortDescription', label: 'Short description', type: 'textarea', section: 'Content' },
      { key: 'paragraph', label: 'Paragraph', type: 'textarea', section: 'Content' },
      { key: 'paragraph2', label: 'Paragraph 2', type: 'textarea', section: 'Content' },
      { key: 'teamParagraph', label: 'Team paragraph', type: 'textarea', section: 'Content' },
    ],
  },
  questions: {
    title: 'Questions',
    description: 'Likert questions attached to elements. Options are computed from weighting.',
    listPath: '/admin/questions',
    createPath: '/admin/questions',
    updatePath: (id) => `/admin/questions/${id}`,
    deletePath: (id) => `/admin/questions/${id}`,
    fields: [
      { key: 'label', label: 'Label', type: 'textarea', required: true, inTable: true, section: 'Basic' },
      {
        key: 'elementId',
        label: 'Element',
        type: 'select',
        required: true,
        inTable: true,
        optionsKey: 'elements',
        section: 'Basic',
        createOnly: true,
      },
      { key: 'order', label: 'Order', type: 'number', required: true, inTable: true, section: 'Basic', defaultValue: 1 },
      { key: 'weighting', label: 'Weighting', type: 'number', required: true, inTable: true, section: 'Scoring', defaultValue: 0.975 },
      { key: 'isNegative', label: 'Negative question', type: 'boolean', inTable: true, section: 'Scoring', defaultValue: false },
      { key: 'concept', label: 'Concept', type: 'textarea', section: 'Scoring' },
    ],
  },
  feedback: {
    title: 'Feedback',
    description: 'Score-band feedback copy used in reports.',
    listPath: '/admin/feedback',
    createPath: '/admin/feedback',
    updatePath: (id) => `/admin/feedback/${id}`,
    deletePath: (id) => `/admin/feedback/${id}`,
    fields: [
      { key: 'scoreMin', label: 'Score min', type: 'number', required: true, inTable: true, section: 'Range', defaultValue: 0 },
      { key: 'scoreMax', label: 'Score max', type: 'number', required: true, inTable: true, section: 'Range', defaultValue: 0 },
      { key: 'level', label: 'Level', type: 'text', required: true, inTable: true, section: 'Copy' },
      { key: 'verb', label: 'Verb', type: 'text', required: true, inTable: true, section: 'Copy' },
      { key: 'adjective', label: 'Adjective', type: 'text', required: true, inTable: true, section: 'Copy' },
      { key: 'focus', label: 'Focus', type: 'text', required: true, inTable: true, section: 'Copy' },
    ],
  },
  matrices: {
    title: 'Group weightings',
    description: 'Score-to-weighting lookup for group calculations.',
    listPath: '/admin/group-weightings-matrices',
    createPath: '/admin/group-weightings-matrices',
    updatePath: (id) => `/admin/group-weightings-matrices/${id}`,
    deletePath: (id) => `/admin/group-weightings-matrices/${id}`,
    fields: [
      { key: 'scoreMin', label: 'Score min', type: 'number', required: true, inTable: true, section: 'Range', defaultValue: 0 },
      { key: 'scoreMax', label: 'Score max', type: 'number', required: true, inTable: true, section: 'Range', defaultValue: 0 },
      { key: 'wtg2', label: 'Weight group 2', type: 'number', required: true, inTable: true, section: 'Weights', defaultValue: 0 },
      { key: 'wtg3', label: 'Weight group 3', type: 'number', required: true, inTable: true, section: 'Weights', defaultValue: 0 },
      { key: 'wtg4', label: 'Weight group 4', type: 'number', required: true, inTable: true, section: 'Weights', defaultValue: 0 },
    ],
  },
};

export const ADMIN_TABS = [
  { id: 'questionnaires' as const, label: 'Questionnaires', icon: '📋' },
  { id: 'elements' as const, label: 'Elements', icon: '🧩' },
  { id: 'questions' as const, label: 'Questions', icon: '❓' },
  { id: 'feedback' as const, label: 'Feedback', icon: '💬' },
  { id: 'matrices' as const, label: 'Weightings', icon: '⚖️' },
];
